### ISSUE TITLE
Input number throws console error on update

### ISSUE THREAD

**Issue by elopez-ag** [DockYard/ember-one-way-controls#108]
Upgrading from 0.8.3 to 1.0.0 I noticed on input type number that when the user enters a not valid character, it removes all the previous value. This behaviour was different in 0.8.3, where the previous value with the wrong character remains in the input (as expected)

With version 1.0.1 just released, the visible behaviour of the input number is the same as the version 0.8.3, but it throws a console error anytime the value gets updated.

The error says "DOMException: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection."

**Comment by msalahz** [comment]
same here

**Comment by martndemus** [comment]
The exception is now fixed by #110, see #16 for invalid character in a number field thing.
