### ISSUE TITLE
Cursor jumps to the second to last position

### ISSUE THREAD

**Issue by jrjohnson** [DockYard/ember-one-way-controls#111]
Using v1.0.1  - When I type in one-way-input my cursor movies back a space... easier shown than described:

https://ember-twiddle.com/7f03b5ab62ff1a340debc81734b1264e

Type anything.

**Comment by martndemus** [comment]
This should now be fixed in `1.0.2`

**Comment by jrjohnson** [comment]
Confirmed.  Thanks!
