### ISSUE TITLE
Cannot edit text when a value is passed in

### ISSUE THREAD

**Issue by buschtoens** [DockYard/ember-one-way-controls#119]
A recent upgrade (I assume the 1.0.0 one) changed the internal logic of keeping track of the `value`.

Before the upgrade, a `value` was passed in and was ignored until it was changed upstream. User edits in the text field just happened.

Now after the upgrade, `{{one-way-input}}` _always_ displays the `value` that is passed in. This means, that I instantly have to sync everything.

In my opinion, this has two major disadvantages to the previous behavior:
1. I now have to manually "buffer" edits, if I don't want them to instantly take effect. Take a search function with query params as an example.
2. Static initial values can't ever change: `{{one-way-input "uneditable"}}`

Is this new behavior intended or just a side-effect? A notice somewhere about this change would have been great.

**Comment by bdmac** [comment]
Noticing issues editing inputs that have initial values as well.

**Comment by efx** [comment]
seeing presumably the same issue running ember-source@2.11

**Comment by algodave** [comment]
In my case I want to initialize `one-way-input` with some value `X`, but `mut` a different value `Y`. It works as long as `X` is `null` or `undefined`, but not when `X` holds some value; in that case the input can't be edited by the user.

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
