### ISSUE TITLE
Input omitting characters on mobile

### ISSUE THREAD

**Issue by kylemellander** [DockYard/ember-one-way-controls#125]
I was using one-way-controls on an app that I was building with ember-cordova.  Specifically we were using the following implementation:

```
{{one-way-textarea
  update=(action (mut model.value))
  value=model.value}}
```

When typing into this field on ios and android, it removes about 50% of the characters.

**Comment by tsteuwer** [comment]
Can you setup a simple github project to recreate this and I can try and look at it?

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
