### ISSUE TITLE
one-way-select  with includeBlank doesn't work as expected with Ember Data relation

### ISSUE THREAD

**Issue by mvuckovic** [DockYard/ember-one-way-controls#127]
I talked about this with Marten Schilstra in Ember Slack #help channel and he told me to submit it here.

one-way-select with includeBlank=true doesn't seem to behave as expected when value is an Ember Data relation.

I would expect that default empty option is selected if value doesn't match any existing option.
This causes DOM and model property to go out of sync.

I made an twiddle example:
https://ember-twiddle.com/67d17a066b822b67057d8f883208ced4?openFiles=templates.application.hbs%2C

Thanks :)

**Comment by Geokoumpa** [comment]
I think what you need `promptIsSelectable=true`

**Comment by martndemus** [comment]
> I think what you need is promptIsSelectable=true

Correct.
