### ISSUE TITLE
Break out dynamic-attribute-bindings into its own repo

### ISSUE THREAD

**Issue by buschtoens** [DockYard/ember-one-way-controls#132]
I just stumbled upon the [`dynamic-attribute-bindings` mixin](https://github.com/DockYard/ember-one-way-controls/blob/master/addon/-private/dynamic-attribute-bindings.js).

I'd like to depend on it in some addons. Would you mind breaking this mixin out into its own repository? Or would you rather have me copy the code and add a notice to the head of the file?

**Comment by martndemus** [comment]
@buschtoens You are free to copy and paste that code, just make sure you also copy the MIT license, from this project.
