### ISSUE TITLE
one-way-input does not update value after two keyEvents

### ISSUE THREAD

**Issue by sukima** [DockYard/ember-one-way-controls#134]
I don't really know the root of this but I can reproduce easily in this twiddle:

https://ember-twiddle.com/538f16c371b8a118abd82363c0f2b862

## Current behavior

Setting value to null, undefined, or empty string *does* clear the input field. But **only** for the first time; subsequent attempts seem to do nothing.

## Expected behavior

Setting value to null, undefined, or empty string should clear the input field

![one-way-input-bug](https://cloud.githubusercontent.com/assets/70075/21301311/74ebb472-c57a-11e6-9246-d0bb715be292.gif)

**Comment by rwjblue** [comment]
The basic issue is that there is nothing to force the input to update. The first time `value` changes from `undefined` to `null` (forcing the rerender that you see after the first), and subsequent updates simply `this.set('value', null)` (which was the previous value) so there is no need to rerender.

Simpest fix is to provide the `update` action to the one-way-input:

```hbs
{{one-way-input value 
  update=(action (mut value)) 
  keyEvents=(hash 13=(action "update"))
}}
```

[See updated demo](https://ember-twiddle.com/bffb2d4d8e7d7e6c77422d53f0063889?openFiles=templates.application.hbs%2C)

**Comment by sukima** [comment]
Oh! Ok. I get it. Thanks.
