### ISSUE TITLE
when sanitize changes initial input, value is modified twice in a single render

### ISSUE THREAD

**Issue by bgentry** [DockYard/ember-one-way-controls#136]
I took the demo gist, updated it to use the `release` channel of ember, and changed the `sanitizeInput` function to just always return a fixed value (thus always changing the initial value to something else):

https://ember-twiddle.com/21941c09a4bb7ac7e8c03f174208806b?openFiles=components.one-way-input.js%2C

Because `sanitizeInput` is called on load (see #135), that causes the following error when the app first renders:

> Assertion Failed: You modified currentValue twice on (generated application controller) in a single render. This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.

My understanding of Ember isn't strong enough to know how to fix this, though 😞

**Comment by martndemus** [comment]
Fixed by removing the action all together. Sanitize your inputs in the update action instead!
