### ISSUE TITLE
one-way-checkbox Visual state not representing data state

### ISSUE THREAD

**Issue by nolaneo** [DockYard/ember-one-way-controls#143]
Hey guys, love this addon, it's super handy 🚀 .

I'm running into an issue where the underlying `checked` state of the checkbox isn't representing its visual state. (i.e. `isChecked=true` but visually the checkbox is in the unchecked state)

This occurs when the `update` action **does not** change the value which determines if the checkbox is on or off.

In this real world example, a user must have at least one checkbox checked, we will reject the update if they attempt to deselect the last checkbox and show a warning instead.

![checked](https://cloud.githubusercontent.com/assets/2514088/22080219/a49b1510-ddb6-11e6-9aef-fcf5ec001d2c.gif)

**Comment by alexander-alvarez** [comment]
here's a gist of what he's talking about https://ember-twiddle.com/39662582dc7072133d32e91e71a3773c?openFiles=templates.application.hbs%2C

**Comment by nolaneo** [comment]
Thanks @alexander-alvarez!

**Comment by peabnuts123** [comment]
I have submitted a PR (above) to resolve this issue

**Comment by Duder-onomy** [comment]
This is still an issue, here is an isolated twiddle for it: 
https://ember-twiddle.com/eb482fce08ef31f9285922114e68f8e4

Notice the checkbox will actually become checked (and its inputs internal `.checked` property set to true) even though we have never changed the `isChecked` attribute to true. 

However, @peabnuts123 branch does not appear to solve the issue, using the branch from #164 
https://ember-twiddle.com/47eef0fedd3a3f1bef470d519a4c15f7

I can still see the checkbox visually appearing checked when clicked, and its input having its `.checked` property set to true. 
Please correct me if I am not understanding the issue, but I would have expected the checkbox to never appear checked if I never set the bound `checked` attr to true?

**Comment by peabnuts123** [comment]
My PR should resolve the described issue, I have personally tested that exact use-case. I can't see how your ember-twiddle is supposed to be using my branch of the code? I have no real experience with ember-twiddle, but it seems to be depending on the regular ember-one-way-controls package. I would suspect your Twiddle is not correctly setup. My PR includes some unit tests to prove the incorrect behaviour in the original code and verifies the correct behaviour in my changes.

I believe you are understanding the issue correctly; do you want to try testing these changes locally?

**Comment by Duder-onomy** [comment]
You could be correct, I am not sure how Twiddle handles dependency resolution, 
The twiddle.json is pointed at your fork, 
```
    "ember-one-way-controls": "peabnuts123/ember-one-way-controls.git#checkbox-prop-fixes"
```
So, I suspect that since that is the only mention of `ember-one-way-controls` in the twiddle then it would have found your fork. If it is pulling the original one way controls repo, then I cannot tell where it would be doing that.

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
