### ISSUE TITLE
Still needed?

### ISSUE THREAD

**Issue by jeroenhouben** [DockYard/ember-one-way-controls#148]
> Note: The cursor jumping issue has been fixed in Ember since 2.3.1.

Is this addon still necessary on Ember versions 2.3.1 and up? What does this addon brings over a normal `<input>` tag?

**Comment by martndemus** [comment]
Convenience

**Comment by jeroenhouben** [comment]
Convenience

**Comment by martndemus** [comment]
See #28

**Comment by jeroenhouben** [comment]
Ah that's what I was looking for, thanks!
