### ISSUE TITLE
Feature: Add Preprocess hook?

### ISSUE THREAD

**Issue by alexander-alvarez** [DockYard/ember-one-way-controls#149]
Would be nice if I didn't have to override `change` and `input` methods to achieve something like this

https://ember-twiddle.com/c1a39ea0e3d922eb95bb8e1d2f96d3d2?openFiles=components.file-name-input.js%2C

**Comment by robbiespeed** [comment]
I'm working on a [fix for cursor jump](https://github.com/robbiespeed/ember-one-way-controls/tree/cursor-jump-fix) that will allow stuff like this. Just need to write some tests, then I'll submit a PR.

You can see in this [twiddle](https://ember-twiddle.com/7160df23741f6454cf873f3b38410d5a) the issue (first 2 inputs) and roughly the ability of the fixed version.

**Comment by john-griffin** [comment]
@robbiespeed this looks promising!

**Comment by brancusi** [comment]
Any updates on this?

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
