### ISSUE TITLE
Support for https://github.com/insin/inputmask-core?

### ISSUE THREAD

**Issue by RobIsHere** [DockYard/ember-one-way-controls#153]
Would be useful for entering Dates etc. See this in react: http://insin.github.io/react-maskedinput/

**Comment by Nikhil783** [comment]
Hi,
Is it possible to create mask example for email address?
Eg It should accepts "@" keyword. abc@example.com

Thanks
Nik

**Comment by RobIsHere** [comment]
Don't know if that's the use case. Because email is not fixed width.

Input masks aren't for validation. That's pretty easy with regex. ember-changeset and its validations if you are looking for this.

If you have to enter lots of dates __/__/__ or fixed width numbers e.g. ___,__ usability is enhanced. Because the user just needs to enter the numbers at the number block. And there remains no room for error.

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
