### ISSUE TITLE
Where is one-way-datetime?

### ISSUE THREAD

**Issue by lcpriest** [DockYard/ember-one-way-controls#154]
There is a one-way-datetime-local.js and one-way-date.js and I was just curious the reasoning behind skipping one-way-datetime.js.

It came up because https://github.com/martndemus/ember-form-for provides a `{{f.datetime-field}}` that tries to look up one-way-datetime.js and fails.

**Comment by RobIsHere** [comment]
I've just seen at MDN that this has been deprecated: https://github.com/whatwg/html/issues/336

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
