### ISSUE TITLE
Still Needed

### ISSUE THREAD

**Issue by MatthewPringle** [DockYard/ember-one-way-controls#155]
Are ember-one-way-controls still needed?

On the linked to videos, which show how to use them with validation, later videos have comments about ember-one-way-controls being 40x slower and now unnecessary.

**Comment by RobIsHere** [comment]
Yes. They are a great help! I haven't done any high-speed-forms yet, why care about perf ;) My opinion.

**Comment by efx** [comment]
@MatthewPringle AFAIK, ember 2.x's default `{{input}}` template mutates values passed in and is not designed as a true component. Thus, `{{one-way-input}}` still serves a useful place in enforcing  the data down actions up paradigm in your app.

**Comment by bstro** [comment]
still needed, especially when using `ember-redux`

**Comment by Turbo87** [comment]
@MatthewPringle in summary: this addon is no longer needed if you use Ember 2.3.1 or above and you don't care about supporting IE9 anymore. If that is the case you can replace most of the components in here with plain `<input>` elements.

**Comment by bstro** [comment]
@Turbo87 does Ember 2.3.1's `{{input}}` helper no longer mutate values passed in?

**Comment by Turbo87** [comment]
@bstro the `{{input}}` thing in Ember does that, but as I said above you can just use plain `<input value={{foo}} oninput={{action (mut foo) value="target.value"}}>` instead

**Comment by efx** [comment]
@Turbo87 do you know of any discussions / best practices around attaching ember events to the native DOM events? From what I have gathered it seems like that could cause difficult bugs.

**Comment by Turbo87** [comment]
I'm not aware of any bugs, I've been using this pattern for quite some time without noticing any issues

/cc @cibernox

**Comment by cibernox** [comment]
@efx Same here, I have stopped myself of using this where possible.
`<input type="text" value={{val}} oninput={{action (mut val) value="target.value"}}>` is much faster, consumes less memory and if you don't support IE9, there is no downside whatsoever, other than this syntax is admittedly more verbose to type.

**Comment by efx** [comment]
@cibernox @Turbo87 , thanks you guys have convinced me to check this pattern out for the clarity, benefits it provides. Though I am on the fence because I just listened to @justinaray's talk on common component errors and he argues for not attaching to native event listeners due to memory clean up issues (https://justinaray.github.io/ember-component-errors/#/listener-cleanup) Am I off base here? also, I can continue the conversation in ember slack.

**Comment by cibernox** [comment]
If you `oninput={{action "whatever"}}` you are doing `element.oninput = function() {  ... }`. That means the event listener lives in the element itself. If the input is removed, the events attached to it are removed as well.

A different story would be something like

```js
Ember.Component.extend({
  didInsertElement() {
    document.querySelector('.something-outside-the-component').addEventListener('click', fn);
  }
});
```

If you add event listener to elements outside a component you must clean after yourself when the component is destroyed. If the event handler is inside the component there should be no problem as that DOM will be removed and any event listener garbage collected.

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
