### ISSUE TITLE
Decimal numbers when using 0.4 and type='number'

### ISSUE THREAD

**Issue by corrspt** [dockyard/ember-one-way-controls#16]
First of all, I'd like to thank you guys for the great work on this addon. I've been using it extensively and it's been very useful.

Since the upgrade to 0.4 I found my self in this situation. I have reached a minimal situation where I have the following in my template:

EDIT: I'm using Ember 2.1, Ember Data 2.2, Ember-cli 1.13.13 and jQuery 2.1.4

```
{{one-way-input value=value update=(action 'changeValue') type='number'}}
```
And in my controller
```js 
import Ember from 'ember';

export default Ember.Controller.extend({
  value: 12,
  actions: {
    changeValue(val) {
      this.set('value', val);
      console.log(val);
    }
  }
});
```
And package.json (part of)
```

"ember-model-validator": "1.2.0",
"ember-one-way-input": "0.4.0",
"ember-pikaday": "0.13.0",
```
What happens is that If type a decimal separator, the content of the input is replaced with nothing (and the `changeValue` function is called with `undefined`. If I type numbers as usual, everything works ok. If I make the `type='text'` the problem does not occur.

What I find more strange is that I have tried the ember-twiddle with the demo and the problem does not occur like this. For the problem to occur in the twiddle (again changing the type to 'number') I need to write two times the decimal separator (like `2..` then the content disappears).

I've also tried copying the code for the component from the [master branch](https://github.com/dockyard/ember-one-way-input/blob/master/addon/components/one-way-input.js) and pasting on the twiddle (to make sure it was using the latest version) but to no avail.

Any thoughts? Thanks a lot.

**Comment by corrspt** [comment]
@poteto, Sorry for pinging, but I've opened issues on github before without the repository owners being notified (or the email when to spam, etc...). I was just trying to make sure you know about the issue.

The issue is not terrible to me, I can workaround by using type='text', was just trying to avoid to change every instance of it. 

Thanks again for the addon!

**Comment by poteto** [comment]
Thanks for reporting this issue, I'll take a look!

**Comment by corrspt** [comment]
Cool, thank you very much @poteto. If you need anything else from me, just ask.

**Comment by corrspt** [comment]
Any luck with this issue, or anything I can do to help? :)

**Comment by corrspt** [comment]
@poteto Just pinging to see If I can help with anything. Or if you had any luck debugging the issue.

**Comment by corrspt** [comment]
@poteto - I've tried @nico-adstage fork and it works, it fixes the issue. Might be worth incorporating the work he's done into the addon.

@nico-adstage. Thanks a lot :+1:

**Comment by poteto** [comment]
Hey guys, apologies for the late response. I'm looking into this bug right now

**Comment by corrspt** [comment]
@poteto Thanks a lot :+1: Happy to see you back!

**Comment by martndemus** [comment]
This issue has not been fixed properly yet. The problem is that Google Chrome actually works according to the HTML5 inputs standard and all other browsers don't.

Workaround for now would be to use a normal text input.
