### ISSUE TITLE
v2.0.1 + ember 1.13 regression

### ISSUE THREAD

**Issue by kellyselden** [DockYard/ember-one-way-controls#165]
I believe the new version regressed 1.13.

https://github.com/kellyselden/ember-tree/issues/223
https://travis-ci.org/kellyselden/ember-tree/builds/258502962

**Comment by kellyselden** [comment]
cc @cibernox

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
