### ISSUE TITLE
Allow for modifying the value in update action

### ISSUE THREAD

**Issue by Techn1x** [DockYard/ember-one-way-controls#170]
So currently I have the following;
```handlebars
{{one-way-number value=condition.durationValue update=(action (mut condition.durationValue))}}
```

Now, when the input is changed, the update action is sent the integer as a string, eg "5"

What I would like to do, is be able to parse that integer in-line without having to define a separate action in my controller, eg something like...
`update=(action (mut condtion.durationValue) (parse-integer value))`
(I have a parse-integer helper)

The trouble I am not sure how to access the value that is passed to update in this way - is there a way to do this?

Alternatively, I could extend the `one-way-number` and make something like `one-way-integer`, but I am not sure what function is best to override to add in the parse int code. Would this be a better way, and what function should I override?

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
