### ISSUE TITLE
input `pattern` doesn't work

### ISSUE THREAD

**Issue by erichonkanen** [DockYard/ember-one-way-controls#177]
I tried adding am html5 `pattern=[0-9]` attribute to an input and it doesn't work (chrome), not sure if related but I'm using one-way-control..

https://stackoverflow.com/questions/12533508/only-allow-numbers-in-input-tage-without-javascript

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.

**Comment by erichonkanen** [comment]
ah good to know! just wrote a contextual form for project that uses all one-way controls.. will update, thanks
