### ISSUE TITLE
Binding values in ember radio

### ISSUE THREAD

**Issue by mehrajpasha** [DockYard/ember-one-way-controls#180]
Hi, I was following this "https://ember-twiddle.com/7e10351fed541a2056b5a3d9b145d915?openFiles=templates.application.hbs%2C" In the place of AVG and MAX I have binding values coming from another JSON object(i.e {{query.choice}})..while I'm getting values in controller I'm getting as {{query.choice}} I need actual binded value

**Comment by martndemus** [comment]
I'm closing this issue due to the fact that we have deprecated this addon. Check the [README](https://github.com/DockYard/ember-one-way-controls) for more info.
