### ISSUE TITLE
"broken" demo from README works!

### ISSUE THREAD

**Issue by steshaw** [DockYard/ember-one-way-controls#183]
The README refers to a [demo on jsbin](http://jsbin.com/juxedi/edit?output). It's supposed to have a problem of jumping to the end of the string when you try to type in the middle. I've tried with the mouse and cursor keys and either way entering a character in the middle of the string works okay here (macOS/Firefox).

Perhaps that demo was updated? Maybe you can point to an older version?

**Comment by martndemus** [comment]
It's still broken in Safari for me.

**Comment by steshaw** [comment]
Right, I checked it in Safari and you're right. Still works in Firefox (Quantum) and Chrome on macOS so this is likely to confuse newcomers like me that come along and follow that link. Just tryin' to help.

**Comment by martndemus** [comment]
We are about to deprecate the whole component. See: #184
