### ISSUE TITLE
onblur (and other events)

### ISSUE THREAD

**Issue by jeffreybiles** [dockyard/ember-one-way-controls#24]
Hey!  Great addon!

With plain old `<input>` I'm able to make an input field that updates the rest of the app when it loses focus:

```js
<input value={{monster.level}} onblur={{action (mut monster.level) value="target.value"}}>
```

Is there a way to replicate this (and other arbitrary events) using `ember-one-way-controls`?

**Comment by martndemus** [comment]
Have you tried:
```js
{{one-way-input blur=(action 'actionThatMutatesMonsterLevel')}}
```

**Comment by rwjblue** [comment]
Ember doesn't listen to `blur` by default ([list of events that are listened to](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/event_dispatcher.js#L65-L91)).

**Comment by rwjblue** [comment]
Per https://developer.mozilla.org/en-US/docs/Web/Events/blur:

> The blur event is fired when an element has lost focus. The main difference between this event and focusout is that only the latter bubbles.

So with Ember components/actions/etc you would use `focusout` which Ember maps to `focusOut`:

```
{{one-way-input focusOut=(action 'lol')}}
```

**Comment by jeffreybiles** [comment]
Thanks, works like a charm!

P.S. Feb 16th there miiiiight be a little video coming out starring this addon :)
