### ISSUE TITLE
Document that since Ember 2.3.1 (unreleased) this addon is not needed anymore

### ISSUE THREAD

**Issue by cibernox** [DockYard/ember-one-way-controls#28]
Since https://github.com/emberjs/ember.js/pull/12877 the cursor position issue is handled by HTMLBars itself, so we can use regular inputs with no problem. It's more verbose but also much faster.

That will probably make this component less needed. Perhaps there is some use case I'm not aware where you want this component over a native `<input>` tag. 

More concise syntax?

**Comment by poteto** [comment]
That is correct, however this addon still remains useful as a wrapper on top of the regular native input, for example having a sanitization method. We are also going to implement other controls in this addon (not just the `input`)

**Comment by rwjblue** [comment]
I was thinking this addon could automatically rewrite `{{one-way-input` into the appropriate plain HTML version.  Lets us provide a super nice consitent API across Ember versions and removes the need for a component at all (read MUCH FASTER)...

**Comment by courajs** [comment]
@rwjblue you mean by hooking into the build pipeline?

**Comment by martndemus** [comment]
@rwjblue When you have time could you outline how that would work?
