### ISSUE TITLE
Contains helper overrides the one provided by ember-composable-helpers

### ISSUE THREAD

**Issue by HeroicEric** [DockYard/ember-one-way-controls#63]
When also using ember-composable-helpers, the `{{contains}}` helper from this addon overrides the `{{contains}}` helper provided by ECH. This is a problem because the arguments are in a different order.

**Comment by poteto** [comment]
Thanks for reporting!

**Comment by rwjblue** [comment]
If only we had local lookup and private helpers :crying_cat_face:
