### ISSUE TITLE
input `type` removal breaking change in 0.6.2

### ISSUE THREAD

**Issue by kellyselden** [DockYard/ember-one-way-controls#85]
As mentioned here: https://github.com/DockYard/ember-one-way-controls/pull/78#issuecomment-211044618

removing `type` on `one-way-input` broke my addon from 0.6.1 to 0.6.2. https://github.com/kellyselden/ember-tree/pull/20.

I'm not sure if you care about semver yet because of 0.x, so is it something you would be willing to revert, or should I change my code? The new way of doing it would involve some duplicated properties:

```hbs
{{#if isCheckbox}}
  {{one-way-checkbox someProperties...}}
{{else}}
  {{one-way-radio somePropertiesRepeated...}}
{{/if}}
```

**Comment by martndemus** [comment]
You don't have to duplicate properties, using the `component` helper
```hbs
{{component (concat "one-way-" type) someProperties...}}
```

**Comment by kellyselden** [comment]
I switched to the new way https://github.com/kellyselden/ember-tree/pull/21. Thanks.

**Comment by martndemus** [comment]
@kellyselden awesome :+1:
