### ISSUE TITLE
Deprecated ember-get-helper

### ISSUE THREAD

**Issue by hyperr** [DockYard/ember-one-way-controls#93]
**Addon:** ember-get-helper
**Repository:** https://github.com/jmurphyau/ember-get-helper
**Notice from Author:** ember-get-helper has been included in Ember 2.0. Use of this package is deprecated and support for Ember 2.0 **will not be maintained**.

**Deprecation Warning**
This addon is used by ember-one-way controls and causing a deprecation warning with the current ember-cli version (2.6.x) and maybe with previous versions.

`DEPRECATION: Overriding init without calling this._super is deprecated. Please call 'this._super.init && this._super.init.apply(this, arguments);' addon: ember-get-helper`

Since ember-get-helper will no longer be maintained, this will result in an error and unusable addon in future ember versions.

**Comment by martndemus** [comment]
Not an issue, the get helper addon is only used when Ember version is < 2.

**Comment by hyperr** [comment]
But I'm using ember 2.6, can you tell me what i'm doing wrong? Thank you!

**Comment by hyperr** [comment]
Oh i know what you mean, i checked the following code line (version check):

https://github.com/jmurphyau/ember-get-helper/blob/master/index.js

As you already mentioned - not an issue!

Thank you for quick response & greate addon!

**Comment by rwjblue** [comment]
We should still get the ember-get-helper addon updated to avoid the deprecation. Can you open an issue over there? I'll try to update and release today...

**Comment by hyperr** [comment]
Yes i was not in the office before, but now i am. I will open an issue at the ember-get-helper repository because the init method is always called and will lead to an error in future releases i think.

Thanks

**Comment by kpfefferle** [comment]
@rwjblue: Do you have contributor access to merge https://github.com/jmurphyau/ember-get-helper/pull/29 and cut a release? It's been sitting over a month with no response or action and all related issues have been closed, so I'm fearing that it may have fallen off the radar.

**Comment by rwjblue** [comment]
Sadly, I do not.

**Comment by bcardarella** [comment]
@rwjblue we can easily fix this

http://www.jobnimbus.com/wp-content/uploads/2013/10/tumblr_m336glqeNC1r04pibo1_500.jpg

**Comment by martndemus** [comment]
@bcardarella This is not the repository they are looking for.

**Comment by bcardarella** [comment]
I still have the power
